project:
  type: website
  output-dir: docs

  preview:
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

website:
  title: "Microbioma del pozol"
  navbar:
    left:
      - href: index.qmd
        text: Taller de Metagenómica centrada en Genomas
      - href: about.qmd
        text: El pozol
      - href: Project.qmd
        text: 01.Espacio de trabajo
      - href: 02.Binning.qmd
        text: 02.MAGs
      - href: gtdbtk.qmd
        text: 03.Taxonomía
      - href: metabolic.qmd
        text: 04.Metabolismo
      - href: Recursos_extra.qmd
        text: Recursos_extra
      - href: Creditos.qmd
        text: Créditos


format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: false

editor: visual

