---
title: "Créditos"
---

**Autoras**: Diana Hernández Oaxaca [\@DianaOaxaca](https://github.com/DianaOaxaca) y Mirna Rosas Vázquez Landa [\@MirnaVazquez](https://github.com/mirnavazquez) .

**Agradecimientos:**

-   Todos los miembros del laboratorio [LandaLab](https://github.com/landalab0) del [Departamento](https://www.icmyl.unam.mx/es/quienes_somos/personal_academico/vazquez-rosas-landa-mirna) de Ecología Molecular y genómica poblacional del ICMyL de la UNAM, por la sugerencias a la mejora de este tutorial.

-   Al M. en C. [Rafael López Sánchez](https://www.ibt.unam.mx/perfil/3986/mc-rafael-lopez-sanchez), por donar los datos de metagenómica del pozol libres de maíz.

-   Al [Dr. Enrique Ibarra-Laclette](http://perfiles.inecol.mx/index.php/home/moleculares/enrique-ibarra-laclette) por la organización del curso y brindar apoyo y acceso al servidor de trabajo.

-   Al [M. en C. Emanuel Villafán de la Torre](http://perfiles.inecol.mx/index.php/home/moleculares/emanuel-villafan-de-la-torre) de la Red de Estudios Moleculares Avanzados del INECOL por la instalación y soporte de las herramientas usadas en este taller.

------------------------------------------------------------------------

El material de esta práctica inicialmente se preparó para los Talleres Internacionales de Bioinformática (**TIB2022**) organizados por la Sociedad Mexicana de Bioinformática (SMB) y la Comunidad de Desarrollo de Software Bioinformático (**CDSB**). Se ha usado en talleres intersemestrales del Instituto de Ciencias del Mar y Limnología (**ICMyL**) de la **UNAM**, el tópico de posgrado **Hackeando las comunidades microbianas**. Cursos intensivos de posgrado del **INECOL**, el taller de metagenómica de la Red Mexicana de Bioinformática **RMB** organizado en el **CIBNOR Junio 2024 y el taller de Ciencia de Frontera en el Tecnológico de Campeche en Agosto de 2024**.

El material se ha ido modificando con el tiempo y sigue en desarrollo. Si tienes sugerencias para agregar y/o modificar este material puedes escribirlas [aquí](https://docs.google.com/document/d/1lwMaJJh9gVbPaQs9mPxSftDhqaFpEqyyZVowtT6Afbg/edit?usp=sharing)

**Contacto**: hoaxacadiana\@gmail.com y mvazquez\@cmarl.unam.mx
